export const Items = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: "89999",
  },
  {
    id: 5,
    category: "laptops",
    title: "Xiaomi [Smartchoice] Notebookpro",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Xiaomi [Smartchoice] Notebookpro ",
    price: "49999",
  },
  {
    id: 7,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Xiaomi Pad 6| Qualcomm Snapdragon 870| ",
    price: "29999",
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 11 (64GB) - White",
    price: "79999",
  },
  {
    id: 6,
    category: "tablets",
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description:
      "Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3",
    price: "19999",
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: "69999",
  },
  {
    id: 4,
    category: "laptops",
    title: "Lenovo IdeaPad Slim 5 ",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
    price: "29999",
  },
  {
    id: 9,
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description:
      "Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)",
    price: "49999",
  },
  {
    id: 8,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description:
      "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ",
    price: "89999",
  },
  {
    id: 10,
    category: "mobiles",
    title: "Samsung Galaxy S24 Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/61Uu3MN8EIL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample1",
    description: "Флагманский смартфон Samsung с ярким экраном 2800 нит",
    price: "129999",
  },
  {
    id: 11,
    category: "mobiles",
    title: "Google Pixel 9",
    imgSrc: "https://m.media-amazon.com/images/I/71B1WsLVmlL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample2",
    description: "Новый Google Pixel с улучшенной камерой и Titan M2 процессором",
    price: "109999",
  },
  {
    id: 12,
    category: "laptops",
    title: "Asus ROG Strix Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/81Pc4vgqWdL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample3",
    description: "Ноутбук для геймеров с NVIDIA GeForce RTX и 240Hz дисплеем",
    price: "179999",
  },
  {
    id: 13,
    category: "laptops",
    title: "MacBook Pro M4",
    imgSrc: "https://m.media-amazon.com/images/I/61Mfp2Gi5jL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample4",
    description: "MacBook с новым процессором M4 для креативных задач",
    price: "199999",
  },
  {
    id: 14,
    category: "tablets",
    title: "Microsoft Surface Pro X2",
    imgSrc: "https://m.media-amazon.com/images/I/71zLCeOr3PL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample5",
    description: "Универсальный планшет с поддержкой 5G и клавиатурой",
    price: "99999",
  },
  {
    id: 15,
    category: "smartwatches",
    title: "Apple Watch Series 10",
    imgSrc: "https://m.media-amazon.com/images/I/81PLqxtrJGL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample6",
    description: "Смарт-часы с отслеживанием глюкозы и AR-функциями",
    price: "69999",
  },
  {
    id: 16,
    category: "vr",
    title: "Meta Quest 3 Lite",
    imgSrc: "https://m.media-amazon.com/images/I/71QgIcwM9lL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample7",
    description: "Доступная версия VR-гарнитуры Meta для домашнего использования",
    price: "59999",
  },
  {
    id: 17,
    category: "smartwatches",
    title: "Garmin Venu 4",
    imgSrc: "https://m.media-amazon.com/images/I/71OgjRA62yL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample8",
    description: "Часы для спортсменов с функциями восстановления и гидратации",
    price: "49999",
  },
  {
    id: 18,
    category: "ai",
    title: "LG AI Kitchen Hub",
    imgSrc: "https://m.media-amazon.com/images/I/61fJGyTAxyL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample9",
    description: "Умный центр кухни с поддержкой голосовых команд",
    price: "79999",
  },
  {
    id: 19,
    category: "smart-home",
    title: "Nest Thermostat Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/71RtGtygtsL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample10",
    description: "Энергоэффективный термостат с поддержкой ИИ",
    price: "29999",
  },
  {
    id: 20,
    category: "mobiles",
    title: "Sony Xperia XZ4",
    imgSrc: "https://m.media-amazon.com/images/I/71xsUPggpHL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3xSample11",
    description: "Смартфон с кинематографическим дисплеем 21:9",
    price: "84999",
  },
];
